### ISSUE TITLE
Multiple edges

### ISSUE THREAD

**Issue by jdirocco** [MDEGroup/jjodel#4]
<img width="514" alt="image" src="https://github.com/MDEGroup/jjodel/assets/7288605/1ee360c7-1383-4619-9a67-b249c3bdd33b">
Edges cannot be distinguished

**Comment by DamianoNaraku** [comment]
This issue was resolved through "edgepoints" they are artificial nodes used to dictate the path of an edge in various modes (bezier arcs, straight lines)
![image](https://github.com/user-attachments/assets/bc02ae05-9632-4963-ac8e-cbe2b5a2529c)
To insert one, select an edge, then on the toolbar a new "Edgepoint" option will appear.
After refreshing the edge once (move the source or the target) the point will appear and can be dragged or customized
![image](https://github.com/user-attachments/assets/57dae1a9-ec87-4dd8-bb95-8bf1abc465e3)

![image](https://github.com/user-attachments/assets/daf81aa7-fa4c-4327-bed7-b10aa9a024b0)
The style of the edge pathing through edgepoints is defined in the options tab of the edge view, not in the edgepoint view.
All the edges using that view will use the same pathing strategy, but a copy of the edge view can be made to allow both straight and curved edges in the same diagram.

**Comment by DamianoNaraku** [comment]
fixed
